apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: todolist
  name: vault-static-secret-mysecret
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: todolist/dbsecret
  refreshAfter: 10s
  destination:
    create: true
    name: mysecret
  rolloutRestartTargets:
  - kind: Deployment
    name: todo-deployment